# - name: Create Grafana repo using template
#   ansible.builtin.template:
#     src: grafana_json_http.service.j2
#     dest: /etc/systemd/system/grafana_json_http.service
#     mode: '0644'
#   run_once: true

# - name: Enable and start Grafana service
#   ansible.builtin.systemd_service:
#     name: grafana_json_http.service
#     enabled: yes
#     state: started
#     daemon_reexec: true
#     daemon_reload: true
#     force: true
#   run_once: true

- name: Garantir que o diretório /var/www/html existe
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create service systemd using template
  ansible.builtin.template:
    src: grafana_json_https.service.j2
    dest: /etc/systemd/system/grafana_json_https.service
    mode: '0644'
  run_once: true

- name: Enable and start service
  ansible.builtin.systemd_service:
    name: grafana_json_https.service
    enabled: yes
    state: started
    daemon_reexec: true
    daemon_reload: true
    force: true
  run_once: true