---
- hosts: localhost
  gather_facts: no

  tasks:

    - include_role:
        name: inventory

- hosts: linux
  gather_facts: no

  tasks:

    # - include_role:
    #     name: grafana_rpm

    # - include_role:
    #     name: grafana_json_service

    # - include_role:
    #     name: grafana_dash
    

    - include_role:
        name: automation_calculator

  handlers:
    - name: Reiniciar Grafana
      ansible.builtin.service:
        name: grafana-server
        state: restarted