- name: Add Grafana YUM repository
  ansible.builtin.get_url:
    url: https://rpm.grafana.com/gpg.key
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-grafana
    mode: '0644'

- name: Create Grafana repo using template
  ansible.builtin.template:
    src: grafana.repo.j2
    dest: /etc/yum.repos.d/grafana.repo
    mode: '0644'

- name: Remove conflicting Grafana packages
  ansible.builtin.dnf:
    name:
      - grafana
      - grafana-pcp
      - grafana-selinux
    state: absent

- name: Exclude grafana from RHEL AppStream repo
  community.general.ini_file:
    path: /etc/yum.repos.d/redhat.repo
    section: rhel-9-for-x86_64-appstream-rpms
    option: exclude
    value: grafana*

- name: Install the latest version of grafana and python3-pip
  ansible.builtin.dnf:
    name: 
      - grafana
      - python3-pip
    state: present

- name: Enable and start Grafana service
  ansible.builtin.systemd_service:
    name: grafana-server
    enabled: yes
    state: started
    force: true
  ignore_errors: true

- name: Install Flask e Flask-HTTPAuth
  ansible.builtin.pip:
    name:
      - flask
      - flask_httpauth
    executable: pip3

- name: Install plugin yesoreyeram-infinity-datasource
  ansible.builtin.command: grafana-cli plugins install yesoreyeram-infinity-datasource
  notify:
    - Reiniciar Grafana