- name: Instalar python3-pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Instalar Flask e Flask-HTTPAuth
  ansible.builtin.pip:
    name:
      - flask
      - flask_httpauth
    executable: pip3